comhavenapp/urls.py
from django.urls import path
from django.conf.urls import url
from . import views as my_views

urlpatterns = [
    path('register/', my_views.register, name='register')

]

comhavenproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from comhavenapp import views
from django.conf.urls import url
from django.contrib.auth.views import LoginView

urlpatterns = [
    # Core
    path('admin/', admin.site.urls),
    path('accounts/', include('comhavenapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    # Page URLs #
    url(r'^$', views.index, name='home'),
    url(r'^accounts$', views.accounts, name='accounts'),
    url(r'^express-login/', views.expresslogins, name='express-login'),
    url(r'^access-control/', views.accesscontrol, name='access-control'),
    url(r'^security-challenges/', views.securitychallenges, name='security-challenges'),
    url(r'^sharedhaven/', views.sharedhaven, name='sharedhaven'),
    url(r'^sharedhaven/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.sharedhaven_token, name='sharedhaven-token'),
    url(r'^generate-password/', views.generatepassword, name='generate-password'),
    url(r'^test-password/', views.test_password, name='test-password'),
    url(r'^register-device/$', views.register_device, name='register-device'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    # Authentication
    url('user_login/', views.user_login, name='user_login'),

    # Page CRUD URLs  #
    url(r'^logins/new_login/$', views.new_login, name='new_login'),
    url(r'^logins/edit/(?P<login_id>\d+)/$', views.login_edit, name='edit'),
    url(r'^logins/delete/(?P<login_id>\d+)/$', views.login_destroy, name='delete'),

    # User Profile
    url(r'^users/user_profile/', views.user_profile, name='user_profile'),
    url(r'^users/user_profile_edit/', views.user_edit, name='user_profile_edit'),
    url(r'^users/user_profile_delete/', views.user_delete, name='user_delete'),
    url(r'^users/user_stats/', views.user_stats, name='user_stats'),

    # Account Recovery
    url(r'^password_reset/done/', views.pass_r_done, name='password_reset_done'),
    url(r'^password_reset/confirm/', views.pass_r_confirm, name='password_reset_confirm'),
    url(r'^accounts/password_reset/$', views.password_reset, name='pass_reset'),
    # Express Login
    url(r'^auto_login/(?P<login_id>\d+)', views.auto_login, name='auto_login'),

    # SharedHaven
    url(r'^send_email/(?P<login_id>\d+)', views.send_email, name='send_email'),

    # Redeem a Rewards

    url(r'^redeem_rewards/', views.redeem_rewards, name='redeem-rewards'),


]

comhavenapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import date

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete='CASCADE')
    email = models.CharField(max_length=100, default='')
    firstname = models.CharField(max_length=100, default='')
    lastname = models.CharField(max_length = 100, default='')
    notes = models.CharField(max_length=200, default='')

    def __str__(self):
        return str(self.user)
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()

class ExpressLoginsSites(models.Model):
    site_name = models.CharField(max_length=50)
    image_path = models.CharField(max_length=200, default='')
    # site_url = models.CharField(max_length=100, default='')
    def __str__(self):
        return self.site_name;

class NewAccountLogin (models.Model):
    login_user = models.ForeignKey(User, on_delete=models.CASCADE, to_field="username", default="user")
    login_target_url = models.CharField(max_length=200)
    login_name = models.CharField(max_length=200)
    login_username = models.CharField(max_length=200)
    login_password = models.CharField(max_length=200, blank=False)
    login_tp = models.CharField(max_length=200, default='')
    login_notes = models.CharField(max_length=200)
    date_inserted = models.DateTimeField(auto_now=True)
    changed_flag = models.BooleanField(default=False)
    issue_flag = models.BooleanField(default=False)
    def __str__(self):
        return self.login_user.username

class Tasks(models.Model):
    tasks = models.CharField(max_length=200, unique=True, default='')
    def __str__(self):
        return str(self.tasks)

class Status(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE, to_field="username", default='')
    user = models.CharField(max_length=50)
    status = models.CharField(max_length=50)
    def __str__(self):
        return str(self.status)

class SecurityChallenges(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default='', to_field='username')
    tasks = models.ForeignKey(Tasks, on_delete=models.CASCADE, default='', to_field='tasks')
    points = models.IntegerField(default=0)
    date_completed = models.DateTimeField(auto_now_add=True)
    date_initiated = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=255, default="Unfinished")
    def __str__(self):
        return str(self.user)
class HistoryLogs(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default='', to_field='username')
    tasks = models.ForeignKey(Tasks, on_delete=models.CASCADE, default='', to_field='tasks')
    points = models.IntegerField(default=0)
    date_completed = models.DateTimeField(auto_now_add=True)
    date_initiated = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=255, default="Unfinished")
    def __str__(self):
        return str(self.user)
class AccessListOfDevices(models.Model):
    acl_user = models.CharField(max_length=30)
    device_name = models.CharField(max_length=30, default='Windows-PC')
    device_model = models.CharField(max_length=30, default='')
    access_id_path = models.CharField(max_length=30, default='')
    device_platform = models.CharField(max_length=30, default='Windows')
    def __str__(self):
        return self.acl_user

# class TempAccounts(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE, to_field='username', default='')
#     temp_uname = models.CharField(max_length=30)
#     temp_pword = models.CharField(max_length=200)
#     ch_flag = models.BooleanField(default=False)
#     def __str__(self):
#         return str(self.user)

class PasswordGenerator(models.Model):
    user  = models.ForeignKey(User, on_delete=models.CASCADE, to_field='username', default='')
    identifier = models.IntegerField()
    pass_result = models.CharField(max_length=200, default='res')
    def __str__(self):
        return self.pass_result

class User_Stats(models.Model):
    user = models.CharField(max_length=30)
    # points_awarded = models.IntegerField()
    overall_points = models.CharField(max_length=200, default=0)
    count = models.IntegerField(default=10)
    def __str__(self):
        return str(self.user)

class Rewards(models.Model):
    reward = models.CharField(max_length=200, default='')
    points_required = models.IntegerField()
    def __str__(self):
        return str(self.reward)

class PerformedTasks(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, to_field='username', default='')
    accounts = models.CharField(max_length=200, default='')
    status = models.CharField(max_length=20, default='')
    def __str__(self):
        return str(self.user)

class WeakPasswords(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, to_field="username", default='')
    login_account = models.CharField(max_length=200, default='')
    login_password = models.CharField(max_length=200, default='')
    login_score = models.CharField(max_length=20, default=0)
    login_strength = models.CharField(max_length=200, default='')
    def __str__(self):
        return str(self.user)

class DuplicatePasswords(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, to_field="username", default='')
    account_id = models.IntegerField(default=0)
    def __str__(self):
        return str(self.user)

class CompromisedPasswords(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, to_field="username", default='')
    login_account = models.CharField(max_length=200, default='')
    login_password = models.CharField(max_length=200, default='')
    def __str__(self):
        return str(self.user)

class OldPasswords(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, to_field="username", default='')
    login_account = models.CharField(max_length=200, default='')
    login_password = models.CharField(max_length=200, default='')
    date_last_inserted = models.DateTimeField(auto_now=True)
    def __str__(self):
        return str(self.user)

comhavenapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import NewAccountLogin, UserProfile, ExpressLoginsSites, PasswordGenerator
from django.core.validators import MinValueValidator
from zxcvbn_password import zxcvbn
from zxcvbn_password.fields import PasswordField, PasswordConfirmationField

from django.contrib.auth.forms import PasswordResetForm as BasePasswordResetForm
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.tokens import default_token_generator


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    # password1 = PasswordField()
    # password2 = PasswordConfirmationField(confirm_with='password1')

    # password1 =  PasswordField()
    # password2 =  PasswordConfirmationField(confirm_with='password1')


    class Meta:
        model = User
        #fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
        fields = ('username', 'email', 'password1', 'password2')


def clean_username(self):
    username = self.cleaned_data.get('username')
    if not username:
        raise forms.ValidationError('username does not exist.')

def clean():
    password = self.cleaned_data.get('password1')

    if password:
        score = zxcvbn(password)['score']
        # score is between 0 and 4
        # raise forms.ValidationError if needed

    return self.cleaned_data

class UserProfileForm(ModelForm):
    email = forms.EmailField(max_length=200, required=False)
    firstname = forms.CharField(max_length=200, required=False)
    lastname = forms.CharField(required=False)
    notes = forms.CharField(required=False)
    class Meta:
        model = UserProfile
        fields = ('email', 'firstname', 'lastname', 'notes')

class NewAccountLoginForm(ModelForm):
    url_choices = (
        ('N/A', 'None'),
        ('https://www.edmodo.com/', 'https://www.edmodo.com'),
        ('https://www.facebook.com/', 'https://www.facebook.com'),
        ('https://github.com/login', 'https://github.com'),
        # ('https://accounts.google.com/AccountChooser/identifier?service=mail&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&flowName=GlifWebSignIn&flowEntry=AccountChooser',
        # 'Gmail'),
        ('https://www.instagram.com/accounts/login/', 'https://www.instagram.com'),
        ('http://lms.uno-r.edu.ph/login/index.php', 'http://lms.uno-r.edu.ph'),
        ('https://app.schoology.com/login', 'https://app.schoology.com'),
        ('https://accounts.spotify.com/en/login/', 'https://accounts.spotify.com'),
        ('https://trello.com/login', 'https://trello.com'),
        ('https://twitter.com/login', 'https://twitter.com'),
        ('http://uis.uno-r.edu.ph/Student/Account/Login', 'http://uis.uno-r.edu.ph'),

    )
    login_name_choices = (
        ('Edmodo', 'Edmodo'),
        ('Facebook','Facebook'),
        ('GitHub', 'GitHub'),
        ('Instagram', 'Instagram'),
        ('LMS', 'LMS'),
        ('Schoology', 'Schoology'),
        ('Spotify', 'Spotify'),
        ('Twitter', 'Twitter'),
        ('UIS', 'UIS'),
        ('Trello', 'Trello'),
    )
    # user_id = forms.CharField(max_length='200', required=False)
    login_target_url = forms.ChoiceField(choices=url_choices)
    login_name = forms.CharField(max_length=200, required=True)
    login_username = forms.CharField(required=True)
    login_password = forms.CharField(widget = forms.PasswordInput(), required=False)
    login_notes = forms.CharField(widget = forms.Textarea, required=False)

    class Meta:
        model = NewAccountLogin
        widgets = {
            'password': forms.PasswordInput(),
        }
        fields = ['login_target_url', 'login_name', 'login_username', 'login_password', 'login_notes']

class SharedHavenForm(forms.Form):
    # from_email = forms.EmailField(required=True)
    to_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea)
    # username = forms.CharField(required=True)
    # password = forms.CharField(widget=forms.PasswordInput)

class PasswordGeneratorForm(ModelForm):
    length_choices = [(i,i) for i in range(6,255)]
    pass_length = forms.ChoiceField(choices=length_choices)
    pass_anagram = forms.ChoiceField(label="Choose an anagram",
                               initial='0',
                               widget=forms.Select(),
                               required=False)
    pass_phrase = forms.CharField(max_length=200, required=True)
    pass_up_lo_case = forms.BooleanField(initial= True, required=False)
    pass_no_case = forms.BooleanField(initial=True, required=False)
    pass_ch_case = forms.BooleanField(initial=True, required=False)
    pass_result = forms.CharField(required=False)
    class Meta:
        model = PasswordGenerator
        fields = ['pass_length', 'pass_phrase', 'pass_up_lo_case','pass_no_case','pass_ch_case']

# # noinspection PyClassHasNoInit
# class PasswordResetForm(BasePasswordResetForm):
#     """A self-reset form for users."""
#
#     def save(self, domain_override='comhaven.herokuapp.com', subject_template_name='registration/password_reset_subject.txt',
#              email_template_name='registration/password_reset_email.html', use_https=False,
#              token_generator=default_token_generator, from_email=None, request=None,
#              html_email_template_name=None,
#              extra_email_context=None):
#         """Override the default in order to return the UID and token for use in the view. This also differs from the
#         default behavior by working with one user at a time.
#         :rtype: list[str]
#         """
#
#         # Get the email. That's why we're here.
#         email = self.cleaned_data["email"]
#
#         # Find the user.
#         try:
#             user = User.objects.get(email=email)
#         except User.DoesNotExist:
#             return None, None
#
#         # Generate token and UID.
#         token = token_generator.make_token(user)
#         uid = urlsafe_base64_encode(force_bytes(user.pk))
#
#         # Get site info.
#         if domain_override:
#             site_title = domain = domain_override
#         else:
#             current_site = request.site
#             site_title = current_site.name
#             domain = current_site.domain
#         # Create the template context.
#         context = {
#             'domain': 'comhaven.herokuapp.com',
#             'email': email,
#             'protocol': 'https' if use_https else 'http',
#             'site_title': site_title,
#             'token': token,
#             'uid': uid,
#             'user': user,
#         }
#
#         if extra_email_context is not None:
#             context.update(extra_email_context)
#
#         # Send the email.
#         # noinspection PyUnusedLocal
#         try:
#             self.send_mail(
#                 subject_template_name,
#                 email_template_name,
#                 context,
#                 from_email,
#                 email
#             )
#         except (SMTPAuthenticationError, SocketError) as e:
#             # TODO: Need to deal with email errors.
#             pass
#
#         # Return the token and uid for use in the view.
#         return token, uid
#
#

# class UpdateProfile(forms.ModelForm):
#     username = forms.CharField(required=True)
#     email = forms.EmailField(required=True)
#     firstname = forms.CharField(required=False)
#     lastname = forms.CharField(required=False)
#
#     class Meta:
#         model = User
#         fields = ('username', 'email', 'firstname', 'lastname')
#
#     def clean_email(self):
#         username = self.cleaned_data.get('username')
#         email = self.cleaned_data.get('email')
#
#         if email and User.objects.filter(email=email).exclude(username=username).count():
#             raise forms.ValidationError('This email address is already in use. Please supply a different email address.')
#         return email
#
#     def save(self, commit=True):
#         user = super(RegistrationForm, self).save(commit=False)
#         user.email = self.cleaned_data['email']
#
#         if commit:
#             user.save()
#
#         return user

comhavenapp/templates/pages/html_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
{% for login in temp %}
<p>Username: {{login.login_username }}</p>
<p>Password: <input type="text" id="pass" name="password" value="{{ login.login_tp }}"> <a href="" onclick="show()">Show</a> </p>
{% endfor %}
</body>
<script>
    function show()
		{
		if( $("#pass").attr("type") == "password" ){
			$("#pass").attr("type", "text");
		}else{
			$("#pass").attr("type", "password");
		}
			return false;
		}
</script>
</html>

comhavenapp/templates/pages/login_edit.html
{% extends 'partial/layout2.html' %}
{% load widget_tweaks %}
{% load static %}
{% block title %} Edit Account Logins {% endblock %}
{% block body %}
<section oncontextmenu="return false">
	<div class="section-body">
		<div class="row">
			<!-- BEGIN  - FORM -->
			<div class="col-sm-12 justify-content-center" id="login-edit-content">
				<div class="card">
					<div class="card-head" style="color: white; background-color: #2b323a;">
				  		<h2 class="text-left" style="margin-left: 20px;">Edit Account</h2>
					</div><!-- end .card-head -->
					<div class="card-body">
						<form class="form" role="form" action="" method="post">
							{% csrf_token %}
							<div class="row">
								<div class="col-sm-6">
									<div class="form-group floating-label">
										{{ form.login_target_url | add_class:'form-control' }}
										<label>Target Url</label>
									</div><!-- end .form-group -->
								</div><!-- end .col-sm-6 -->
								<div class="col-sm-6">
									<div class="form-group floating-label">
										{{ form.login_name | add_class:'form-control' }}
										<label>Site Name</label>
									</div><!-- end .form-group -->
								</div><!-- end .col-sm-6 -->
								<div class="col-sm-6">
									<div class="form-group floating-label">
										{{ form.login_username | add_class:'form-control'}}
										<label>Username</label>
									</div><!-- end .form-group -->
								</div><!-- end .col-sm-6 -->

								<div class="col-sm-6">
									{% if login.issue_flag %}
									<div class="col-sm-9" id="fpassword_field">
										<div class="form-group floating-label">
											<input type="password" class="form-control" id="id_login_password" name="login_password3" value="{{ login.login_tp }}" required="False">
											<!--{{ form.login_password | add_class:'form-control'}}-->
											<label>Password</label>
										</div><!-- end .form-group -->
									</div>
									{% elif not login.issue_flag  %}
										<div class="col-sm-9" id="ftpassword_field">
										<div class="form-group floating-label">
											<input type="password" readonly class="form-control" id="id_login_password" name="login_password3" value="{{ login.login_tp }}" required="False">
											<!--{{ form.login_password | add_class:'form-control'}}-->
											<label>Password</label>
										</div><!-- end .form-group -->
									</div>
									{% endif %}
									<div class="col-sm-1" id="copyBtn">
										<i class="fa fa-clipboard" data-toggle="tooltip" title="Copy to Clipboard" onclick="copy()" data-placement="top" style="margin-top:30px;"></i>
									</div>
									<div class="col-sm-1" id="eyeBtn">
										<i class="fa fa-eye-slash" id="show_eye" onclick="show()" data-toggle="tooltip" title="Show/Hide Password"  style="margin-top:30px;"></i>
									</div><!-- end .col-sm-1 -->
									<div class="col-sm-1" id="genBtn">
										<a href="{% url 'generate-password' %}"><i class="fa fa-key" style="margin-top:30px;" data-toggle="tooltip" title="Generate a Password"></i></a>
									</div><!-- end .col-sm-1 -->
								</div><!-- end .col-sm-6 -->
								<div class="col-sm-6">
									<div class="form-group floating-label">
										{{ form.login_notes | add_class:'form-control' | attr:'rows:4'}}
										<label>Notes</label>
									</div><!-- end .form-group -->
								</div><!-- end .col-sm-6 -->
								<div class="col-sm-6" style="padding: 25px;">
									<div class="form-group">
										<label>Password Strength</label><br>
										<div class="progress">
											<div id="StrengthProgressBar" class="progress-bar"></div>
										</div><!-- end .progress -->
									</div><!-- end .form-group -->
								</div><!-- end .col-sm-6 -->
								<div class="col-md-12">
									<hr><!-- !line-break-->
									<div class="card-actionbar-row">
										<input type="submit" class="btn btn-default ink-reaction" value="Save" style="color: white; background-color: #2b323a;" id="btnSave">
										<a href="{% url 'accounts' %}">
											<input type="button" class="btn btn-secondary ink-reaction" value="Cancel" id="btnCancel">
										</a>
									</div><!-- end .card-actionbar-row -->
								</div><!-- end col-md-12 -->
							</div><!-- end .row -->
						</form><!-- end form -->
					</div><!--end .card-body -->
				</div><!--end .card -->
			</div><!--end .col -->
			<!-- END FORM - TIME ON SITE -->
		</div><!--end .row -->
	</div><!--end .section-body -->
</section><!-- end section -->
<script src="{% static 'js/core/App.js' %}"></script>
<script src="{% static 'js/libs/jquery/jquery-1.11.2.min.js' %}"></script>
<script src="{% static 'js/core/AppForm.js' %}"></script>
<script src="{% static 'js/core/pass_con.js' %}"></script>
<script src="{% static 'js/libs/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'js/libs/jquery/jquery-1.11.2.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/1.0/zxcvbn.min.js"></script>
<script src="{% static 'js/core/zxcvbn-bootstrap-strength-meter.js' %}"></script>
<script>
	function show()
		{
		if( $("#id_login_password").attr("type") == "password" ){
			$("#id_login_password").attr("type", "text");
			$("#show_eye").attr("class", "fa fa-eye-slash");
		}else{
			$("#id_login_password").attr("type", "password");
			$("#show_eye").attr("class", "fa fa-eye");
		}
			return false;
		}
	function copy() {
	  /* Get the text field */
	  var copyText = document.getElementById("id_login_password");

	  /* Select the text field */
	  copyText.select();

	  /* Copy the text inside the text field */
	  document.execCommand("copy");

	}
</script>
<script type="text/javascript">
	$(document).ready(function()
	{
		$("#StrengthProgressBar").zxcvbnProgressBar({
			passwordInput: "#id_login_password",
			ratings: ["Very Weak", "Weak", "Medium", "Strong", "Very strong"],
		});

	});
</script>
{% endblock %}<!-- endfor -->

comhavenapp/templates/pages/new_login.html
{% extends 'partial/layout2.html' %}
{% load widget_tweaks %}
{% load static %}
{% block title %} Add New Account Logins {% endblock %}
{% block body %}
<section>
	<div class="section-body">
		<div class="row">
			<!-- BEGIN  - FORM -->
			<div class="col-sm-12 justify-content-center" id="login_content">
				<div class="card">
					<div class="card-head" style="color: white; background-color: #2b323a;">
				  		<h2 class="text-left" style="margin-left: 20px;"> Add new account</h2>
					</div><!-- end .card-head -->
					<div class="card-body">
						<form class="form" role="form" action="" method="post">
							{% csrf_token %}
							<div class="row">
								<div class="col-sm-6">
									<div class="form-group floating-label">
										{{ form.login_target_url | add_class:'form-control' }}
										<label>Target Url</label>
									</div><!-- end .form-group -->
								</div><!-- end .col-sm-6 -->
								<div class="col-sm-6">
									<div class="form-group floating-label">
										<!--{{ form.login_name | add_class:'form-control' }}-->
										<input type="text" list="accounts" name="login_name" class="form-control" id="id_login_name">
										<datalist id="accounts">
											<option value="Edmodo">
											<option value="Facebook">
											<option value="GitHub">
											<option value="Instagram">
											<option value="LMS">
											<option value="Schoology">
											<option value="Spotify">
											<option value="Trello">
											<option value="Twitter">
											<option value="UIS">
										</datalist><!-- end datalist -->
										<label>Site Name</label>
									</div><!-- end .form-group -->
								</div><!-- end .col-sm-6 -->
								<div class="col-sm-6">
									<div class="form-group floating-label">
										{{ form.login_username | add_class:'form-control'}}
										<label>Username</label>
									</div><!-- end .form-group -->
								</div><!-- end .col-sm-6 -->
								<div class="col-sm-6" id="fpassword_field">
									<div class="col-sm-11">
										<div class="form-group floating-label">
											{{ form.login_password | add_class:'form-control'}}
											<label>Password</label>
										</div><!-- end .form-group -->
									</div><!-- end .col-sm-11 -->
									<div class="col-sm-1">
										<i class="fa fa-eye-slash" id="show_eye" onclick="show()" data-toggle="tooltip" title="Show/Hide Password" style="margin-top:30px;"></i>
									</div><!-- end .col-sm-1 -->
								</div><!-- end .col-sm-6 -->

								<div class="col-sm-6">
									<div class="form-group floating-label">
										{{ form.login_notes | add_class:'form-control' | attr:'rows:4'}}
										<label>Notes</label>
									</div><!-- end .form-group -->
								</div><!-- end .col-sm-6 -->
								<div class="col-sm-6" style="padding: 25px;">
									<div class="form-group">
										<label>Password Strength</label><br>
										<div class="progress">
											<div id="StrengthProgressBar" class="progress-bar"></div>
										</div><!-- end .progress -->
									</div><!-- end .form-group -->
								</div>
								<div class="col-md-12">
									<hr><!-- !line-break -->
									<div class="card-actionbar-row">
										<input type="submit" class="btn btn-default ink-reaction" value="Save" style="color: white; background-color: #2b323a;" id="btnSave">
										<a href="{% url 'accounts' %}">
											<input type="button" class="btn btn-secondary ink-reaction" value="Cancel" id="btnCancel">
										</a>
									</div><!-- end .card-actionbar-row-->
								</div><!-- end .col-md-12 -->
							</div><!-- end .row -->
						</form><!-- end form -->
					</div><!--end .card-body -->
				</div><!--end .card -->
			</div><!--end .col -->
			<!-- END FORM - TIME ON SITE -->
		</div><!--end .row -->
	</div><!--end .section-body -->
</section><!-- end section -->
<script src="{% static 'js/libs/jquery/jquery-1.11.2.min.js' %}"></script>
<script src="{% static 'js/libs/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'js/core/zxcvbn-bootstrap-strength-meter.js' %}"></script>
<script>
	function show()
		{
		if( $("#id_login_password").attr("type") == "password" ){
			$("#id_login_password").attr("type", "text");
			$("#show_eye").attr("class", "fa fa-eye-slash");
		}else{
			$("#id_login_password").attr("type", "password");
			$("#show_eye").attr("class", "fa fa-eye");
		}
			return false;
		}
</script>
<script type="text/javascript">
	$(document).ready(function()
	{
		$("#StrengthProgressBar").zxcvbnProgressBar({
			passwordInput: "#id_login_password",
			ratings: ["Very Weak", "Weak", "Medium", "Strong", "Very strong"],
		});

	});
</script>
{% endblock %}<!-- endblock -->

comhavenapp/templates/pages/register_device_email_template.html
{% autoescape off %}
    click this link to register your device. http://127.0.0.1:8000/register-device/
{% endautoescape %}

comhavenapp/templates/pages/share_credentials_template.html
{% autoescape off %}
    Dear Trusted User,
        To initiate the account credential access in {{ user.username }} ComHaven Account,
        click the link below:

        http://{{domain}}{% url 'sharedhaven-token' uidb64=uid token=token %}

        If clicking the link above doesn't work, please copy and paste the URL in a new browser
        window instead.

    Sincerely,
    The Fighting Dugtrio Team
{% endautoescape %}